### ISSUE TITLE
Here’s the translation:

### ISSUE THREAD

**Issue by hou-wen-qing** [wengkeii/gps-anomaly-detection#2]
Regarding the data issue: Since your data format differs from the official data format, I would like to ask how your data was processed?

**Comment by wengkeii** [comment]
Using the official data, I considered them as 'labelled' and 'unlabelled' dataset, where the labelled dataset are the ones with the start and end timings of trajectories provided. Then I combined the data points with specific timestamps and GPS coordinates of the labelled dataset into trajectories based on the start and end timings using Geopandas. Afterwards, I did feature engineering to add new data columns such as the distance, duration and speed for each trajectory as well.
